### PR TITLE
Move from attachments to blocks

### LINKED ISSUE #36: Use Slack blocks payload
[`attachments` is deprecated](https://api.slack.com/reference/messaging/payload) for the new `blocks`-style. It's pretty trivial to convert.

I also notice slack-message-building is currently duplicated in 3/4 places throughout this project, having a central function/library would make this work much easier.

### PR DESCRIPTION
**Pull request by pbrisbin**
This may be a bit WIP as I can't figure out how to recover colors under the
blocks version. Does anyone know?

Closes #36.

### CODE REVIEW

**Comment by davidhulse** [comment]
The only thing I see is potentially using an [image element](https://api.slack.com/reference/block-kit/block-elements#image) that contains the color

**Comment by pbrisbin** [comment]
Hmm. At that point, what about prefixing the messages with an emoji to represent what the colors were doing before?

STATUS_COLORS = {
    'CREATE_COMPLETE': ":heavy_check_mark:" ,
    'CREATE_IN_PROGRESS': ":heavy_check_mark:" ,
    'CREATE_FAILED': ":x:" ,
    # ...
}

> :x: Stack error at cg-app-bucket/whatever/whatever

?

**Comment by pbrisbin** [comment]
FYI, this [block it builder](https://app.slack.com/block-kit-builder/T03CTC00T#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E2%9D%8C%20Stack%20error%20in%20%60some-bucket/some-key%60:%5Cn%60%60%60%5CnThe%20raw%20error%20message%5Cn%60%60%60%22%7D%7D%5D%7D) thing is pretty cool for iterated on this.

**Comment by davidhulse** [comment]
I like that

**Review by davidhulse — APPROVED** [review]

**Comment by pbrisbin** [comment]
FYI, I might hold off on merging this. I just deployed in my system and didn't get a notification when testing. I haven't had a chance to investigate but it could be a bug here. Will report back, hopefully next week.

**Comment by pbrisbin** [comment]
OK, I've successfully tested this after fixing a small python3 bug (that exists on `master`). I have to step away and can't make the PR right now, but it's just:

```diff
commit 07b8c2c94534171fb5a701b6a5cb730c5b52b739
Author: patrick brisbin <pbrisbin@gmail.com>
Date:   Fri Dec 17 15:32:01 2021 -0500

    Fix python3 import for urllib.parse

diff --git a/cf-notify/lambda_notify.py b/cf-notify/lambda_notify.py
index b68dffd..05aa41a 100644
--- a/cf-notify/lambda_notify.py
+++ b/cf-notify/lambda_notify.py
@@ -1,5 +1,6 @@
 import json
 import shlex
+import urllib.parse
 import urllib.request
 import re
 import os
@@ -134,4 +135,4 @@ def get_stack_url(stack_id):
     }
 
     return ('https://{region}.console.aws.amazon.com/cloudformation/home?region={region}#/stack/detail?{query}'
-            .format(region=region, query=urllib.urlencode(query)))
+            .format(region=region, query=urllib.parse.urlencode(query)))
```

**Comment by pbrisbin** [comment]
:point_up: opened in #41.

**Comment by rmmeans** [comment]
Sorry, are we ready to merge now @pbrisbin ?

**Comment by pbrisbin** [comment]
Yes, thanks!

**Pull request merged**
